#!/usr/bin/env bash
com=$1
app=$2

function update {
if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
else
pacman -Suy
fi
}

function updateall {
if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
else
yes | pacman -Suy
fi
}

function install {
if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
else
pacman -Sy $app
fi
}

function build {

makepkg --syncdeps
sudo pacman -U *.xz
}

function remove {
if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
else
pacman -Rsu $app
fi
}

function query {
	if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
else
	pacman -Fy
	pacman -F $app
fi
}

function help {
 echo "Package to automate install, update and remove packages from Arch System"
 echo "update: Updates system without automatic yes"
 echo "updateall: Updates system with automatic yes"
 echo "install: Installs package from pacman"
 echo "remove: removes package from pacman"
 echo "query: Queries pacman for package"
 echo "build: Builds package from AUR and installs pacakge"
  
}
if [ "$com" == update ]
then
	update

elif [ "$com" == updateall ]
then
	updateall

elif [ "$com" == install ]
then
	install

elif [ "$com" == remove ]
then
	remove

elif [ "$com" == query ]
then
	query

elif [ "$com" == build ]
then
	build
else
	echo "Please provide one of the following updateall,update,build,install,query or remove"
fi
